/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as CollectorRouteRouteImport } from './routes/collector/route'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminBranchesRouteImport } from './routes/admin/branches'
import { Route as AdminCollectorsRouteImport } from './routes/admin/collectors'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminDepositsRouteImport } from './routes/admin/deposits'
import { Route as AdminNewUserRouteImport } from './routes/admin/new-user'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorRouteRoute = CollectorRouteRouteImport.update({
  id: '/collector',
  path: '/collector',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCollectorsRoute = AdminCollectorsRouteImport.update({
  id: '/collectors',
  path: '/collectors',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewUserRoute = AdminNewUserRouteImport.update({
  id: '/new-user',
  path: '/new-user',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/collector': typeof CollectorRouteRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/collectors': typeof AdminCollectorsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/new-user': typeof AdminNewUserRoute
  '/admin/reports': typeof AdminReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/collector': typeof CollectorRouteRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/collectors': typeof AdminCollectorsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/new-user': typeof AdminNewUserRoute
  '/admin/reports': typeof AdminReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/collector': typeof CollectorRouteRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/collectors': typeof AdminCollectorsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/new-user': typeof AdminNewUserRoute
  '/admin/reports': typeof AdminReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/collector'
    | '/admin/audit'
    | '/admin/branches'
    | '/admin/collectors'
    | '/admin/dashboard'
    | '/admin/deposits'
    | '/admin/new-user'
    | '/admin/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/collector'
    | '/admin/audit'
    | '/admin/branches'
    | '/admin/collectors'
    | '/admin/dashboard'
    | '/admin/deposits'
    | '/admin/new-user'
    | '/admin/reports'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/collector'
    | '/admin/audit'
    | '/admin/branches'
    | '/admin/collectors'
    | '/admin/dashboard'
    | '/admin/deposits'
    | '/admin/new-user'
    | '/admin/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CollectorRouteRoute: typeof CollectorRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector': {
      id: '/collector'
      path: '/collector'
      fullPath: '/collector'
      preLoaderRoute: typeof CollectorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/collectors': {
      id: '/admin/collectors'
      path: '/collectors'
      fullPath: '/admin/collectors'
      preLoaderRoute: typeof AdminCollectorsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/new-user': {
      id: '/admin/new-user'
      path: '/new-user'
      fullPath: '/admin/new-user'
      preLoaderRoute: typeof AdminNewUserRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBranchesRoute: typeof AdminBranchesRoute
  AdminCollectorsRoute: typeof AdminCollectorsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminNewUserRoute: typeof AdminNewUserRoute
  AdminReportsRoute: typeof AdminReportsRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBranchesRoute: AdminBranchesRoute,
  AdminCollectorsRoute: AdminCollectorsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDepositsRoute: AdminDepositsRoute,
  AdminNewUserRoute: AdminNewUserRoute,
  AdminReportsRoute: AdminReportsRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CollectorRouteRoute: CollectorRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
